[package]
name = "motiongfx_vello"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = { version = "0.12", default-features = false }
bevy_app = { version = "0.12", default-features = false }
bevy_math = { version = "0.12", default-features = false }
bevy_transform = { version = "0.12", default-features = false }
bevy_pbr = { version = "0.12", default-features = false }
bevy_asset = { version = "0.12", default-features = false }
bevy_log = { version = "0.12", default-features = false }
bevy_utils = { version = "0.12", default-features = false }
bevy_reflect = { version = "0.12", default-features = false }
motiongfx_core = { version = "0.1.0", path = "../motiongfx_core" }
bevy_vello_renderer = { git = "https://github.com/nixon-voxell/bevy_vello_renderer", rev = "edad3a50d1238ca9a0bf4a8c87b8574ed775be1d" }
